### ISSUE TITLE
Dependency Problems

### ISSUE THREAD

**Issue by trietmnj** [HydrologicEngineeringCenter/nsi-ui#11]
Two dependency issues:

Requires package "citysdk" that is not in the master branch. Unsure if pushing node_modules changes to github is wise since it is in .gitignore

Unable to start development server unless "react-scripts" is turned into an executable. Current fix on local container is:
`chmod +x node_modules/.bin/react-scripts`
Unsure how to persist change to github.

**Comment by HenryGeorgist** [comment]
@trietmnj good comments. I deleted node modules, you are right we should not be tracking those, I committed before i added gitignore... smh. 

citysdk is a way i was using to get the state boundaries. i think we should probably move back to that way instead of directly referencing the shapefile.  right now it is not necessary, i think we could remove it by fixing the download plugin which has an include census from citysdk in it. Or we could add the usage back in now that i have the basics working in the application.

I dont think i have to turn the react-scripts into an executable, but maybe i am missing something... 

My reccomendation is to create one issue per issue, dont bundle - that way we can close each one when completed.

**Comment by HenryGeorgist** [comment]
i pulled from github after deleting the node modules, and got a failure on the react scripts start. after an npm update, the application started just fine.

**Comment by trietmnj** [comment]
One problem per issue makes sense, will do from now on. On a fresh pull, I'm unable to do `npm start` even after `npm update`

`npm install react-scripts --save` seems to fix it. My docker image is based on node-alpine though.

**Comment by HenryGeorgist** [comment]
@trietmnj is this issue still open?

**Comment by trietmnj** [comment]
Don't think so. At least not for the env on my end.
