### ISSUE TITLE
404 from selecting Puerto Rico

### ISSUE THREAD

**Issue by HenryGeorgist** [HydrologicEngineeringCenter/nsi-ui#29]
if you select PR, then choose download you get an internal server error. you get to the 404 page ultimately, which has a link to "go home" which triggers a further fail state.

**Comment by trietmnj** [comment]
Looks like this might be due to data from the region not available in the backend db. I can do a check to see if data is available. If not I can change the text to say it's not available and remove the download button.

https://nsi-dev.sec.usace.army.mil/nsiapi/export/state/nsiv2_72.gpkg

**Comment by HenryGeorgist** [comment]
That is correct. we do not have data in the NSI base layer from 2019 for PR. That is our fundamental problem here, we could not add the feature to the map for download. I think that would require a different solution than we are currently using for how we display the states - I am open to ideas.

**Comment by trietmnj** [comment]
http://degas.en.kku.ac.th/courses/198473/resource/Don't%20Make%20Me%20Think,%20Steve%20Krug,%20Revisited,%203rd%20Edition.pdf 

So I've been reading this book on designing interfaces. One of the main key point is that the user shouldn't think about what's going on, every action should be intuitive. Based on that, I can think of 2 options on the top of my head:

1) Remove the ingest state data prior to render. It won't show the outlines on the states where data isn't available. It's a workable solution, but if a user need data for that state, then it wouldn't be intuitive. They would ask "why can't I download this data?" The lack of data availability would not be an answer they would naturally come to without consulting another resource.

2) Show outlines on states where data would not be available. Once the user click on it, if the data isn't available, then remove the download button and display a prompt saying that data isn't available and mention resources where they can learn more about the issue. I think this is better for usability in term of "don't make the user think" but it could be a negative in performance since implementing this would mean adding another call to the backend server to do the data availability check. I'm not convince adding that extra call would be too expensive though.

**Comment by trietmnj** [comment]
Well, for #2, there is also an option to add a static list of states where data is not available and avoid that additional call entirely. That doesn't seem like a good programming practice though. Any update to the backend db would need manual coding update to the front-end web app.

**Comment by trietmnj** [comment]
Another option for #2, and this is a little bit out there, but write a separate tool to generate a list of unavailable states, store it somewhere accessible to the web-app. Periodically update the list. The web-app can query the list every time it initialize, so it would not be on every selection. That would solve any potential performance issue. This would be quite a bit more work though.

**Comment by HenryGeorgist** [comment]
First, thanks for reading about UI/UX!

I think we do simple first. Right now PR is not available, in 6 months, it will be. Right now we don't have an api call for if a state is available, so id rather not add that to the api.  
I vote we put some logic like the Alaska logic in for PR, and just change the message and remove the buttons. "Puerto Rico Is not currently Available for download"
